### PR TITLE
Release 3.2.2

### PR DESCRIPTION
**Pull request by rlepinski**
Unity's JSON cant handle a Dictionary so we have to work around this by passing model objects back and forth. PushMessage expects an Array of Extra. An Extra is defined by { string key, string value}. So we need to format the json to be something like:

```
"extras": [ {"key": "some key", "value": "some value" }, ...]
```

### CODE REVIEW

**Comment by madelgi** [comment]
🌵

**Comment by BrianBatchelder** [comment]
:cookie:

**Comment by hcrowell** [comment]
🍊

**Comment by rlepinski** [comment]
👍

**Pull request merged**
