### PR TITLE
Fixing typos

### PR DESCRIPTION
**Pull request by linkmh**
airsip -> airship

### CODE REVIEW

**Comment by BrianBatchelder** [comment]
Add to whitelist

**Comment by BrianBatchelder** [comment]
Ok to test

**Comment by BrianBatchelder** [comment]
retest this please

**Comment by BrianBatchelder** [comment]
@linkmh - are these strings used by apps? If so, we might need to keep the old ones around and deprecate them to be removed in a future release.

**Comment by BrianBatchelder** [comment]
retest this please

**Comment by linkmh** [comment]
I didn't see either of those used anywhere. Rather, the corrected version of those strings are used.

**Comment by BrianBatchelder** [comment]
test this please

**Comment by BrianBatchelder** [comment]
ok to test

**Pull request merged**
